<?php

namespace Database\Seeders;

use App\Models\Catalog;
use Illuminate\Database\Seeder;

class CatalogSeeder extends Seeder
{
    /**
     * Catalog structure from the production demo catalog.
     *
     * @var array<int, array{id:int, key:string, image:?string, parent_id:?int}>
     */
    private const CATALOG = [
        ['id' => 1, 'key' => 'technology', 'image' => 'test-technology.svg', 'parent_id' => null],
        ['id' => 2, 'key' => 'software_development', 'image' => null, 'parent_id' => 1],
        ['id' => 3, 'key' => 'web_hosting', 'image' => null, 'parent_id' => 1],
        ['id' => 4, 'key' => 'cybersecurity', 'image' => null, 'parent_id' => 1],
        ['id' => 5, 'key' => 'ai_data', 'image' => null, 'parent_id' => 1],
        ['id' => 6, 'key' => 'hardware_gadgets', 'image' => null, 'parent_id' => 1],
        ['id' => 7, 'key' => 'business_finance', 'image' => 'test-business-and-finance.svg', 'parent_id' => null],
        ['id' => 8, 'key' => 'banks_credit', 'image' => null, 'parent_id' => 7],
        ['id' => 9, 'key' => 'accounting', 'image' => null, 'parent_id' => 7],
        ['id' => 10, 'key' => 'insurance', 'image' => null, 'parent_id' => 7],
        ['id' => 11, 'key' => 'real_estate', 'image' => null, 'parent_id' => 7],
        ['id' => 12, 'key' => 'investments', 'image' => null, 'parent_id' => 7],
        ['id' => 13, 'key' => 'shopping', 'image' => 'test-shopping.svg', 'parent_id' => null],
        ['id' => 14, 'key' => 'fashion_stores', 'image' => null, 'parent_id' => 13],
        ['id' => 15, 'key' => 'electronics_stores', 'image' => null, 'parent_id' => 13],
        ['id' => 16, 'key' => 'marketplaces', 'image' => null, 'parent_id' => 13],
        ['id' => 17, 'key' => 'office_supplies', 'image' => null, 'parent_id' => 13],
        ['id' => 18, 'key' => 'gifts_flowers', 'image' => null, 'parent_id' => 13],
        ['id' => 19, 'key' => 'health_medicine', 'image' => 'test-health-and-medicine.svg', 'parent_id' => null],
        ['id' => 20, 'key' => 'clinics', 'image' => null, 'parent_id' => 19],
        ['id' => 21, 'key' => 'pharmacy', 'image' => null, 'parent_id' => 19],
        ['id' => 22, 'key' => 'dentistry', 'image' => null, 'parent_id' => 19],
        ['id' => 23, 'key' => 'mental_health', 'image' => null, 'parent_id' => 19],
        ['id' => 24, 'key' => 'telemedicine', 'image' => null, 'parent_id' => 19],
        ['id' => 25, 'key' => 'education', 'image' => 'test-education.svg', 'parent_id' => null],
        ['id' => 26, 'key' => 'universities', 'image' => null, 'parent_id' => 25],
        ['id' => 27, 'key' => 'online_courses', 'image' => null, 'parent_id' => 25],
        ['id' => 28, 'key' => 'language_schools', 'image' => null, 'parent_id' => 25],
        ['id' => 29, 'key' => 'tutoring', 'image' => null, 'parent_id' => 25],
        ['id' => 30, 'key' => 'science_resources', 'image' => null, 'parent_id' => 25],
        ['id' => 31, 'key' => 'travel_transport', 'image' => 'test-travel-and-transport.svg', 'parent_id' => null],
        ['id' => 32, 'key' => 'hotels', 'image' => null, 'parent_id' => 31],
        ['id' => 33, 'key' => 'airlines', 'image' => null, 'parent_id' => 31],
        ['id' => 34, 'key' => 'car_rental', 'image' => null, 'parent_id' => 31],
        ['id' => 35, 'key' => 'logistics', 'image' => null, 'parent_id' => 31],
        ['id' => 36, 'key' => 'travel_guides', 'image' => null, 'parent_id' => 31],
        ['id' => 37, 'key' => 'food_dining', 'image' => 'test-food-and-dining.svg', 'parent_id' => null],
        ['id' => 38, 'key' => 'restaurants', 'image' => null, 'parent_id' => 37],
        ['id' => 39, 'key' => 'coffee_shops', 'image' => null, 'parent_id' => 37],
        ['id' => 40, 'key' => 'grocery_delivery', 'image' => null, 'parent_id' => 37],
        ['id' => 41, 'key' => 'recipes', 'image' => null, 'parent_id' => 37],
        ['id' => 42, 'key' => 'catering', 'image' => null, 'parent_id' => 37],
        ['id' => 43, 'key' => 'home_garden', 'image' => 'test-home-and-garden.svg', 'parent_id' => null],
        ['id' => 44, 'key' => 'furniture', 'image' => null, 'parent_id' => 43],
        ['id' => 45, 'key' => 'interior_design', 'image' => null, 'parent_id' => 43],
        ['id' => 46, 'key' => 'home_repair', 'image' => null, 'parent_id' => 43],
        ['id' => 47, 'key' => 'gardening', 'image' => null, 'parent_id' => 43],
        ['id' => 48, 'key' => 'smart_home', 'image' => null, 'parent_id' => 43],
        ['id' => 49, 'key' => 'entertainment_arts', 'image' => 'test-entertainment-and-arts.svg', 'parent_id' => null],
        ['id' => 50, 'key' => 'movies', 'image' => null, 'parent_id' => 49],
        ['id' => 51, 'key' => 'music', 'image' => null, 'parent_id' => 49],
        ['id' => 52, 'key' => 'games', 'image' => null, 'parent_id' => 49],
        ['id' => 53, 'key' => 'museums', 'image' => null, 'parent_id' => 49],
        ['id' => 54, 'key' => 'events', 'image' => null, 'parent_id' => 49],
        ['id' => 55, 'key' => 'news_media', 'image' => 'test-news-and-media.svg', 'parent_id' => null],
        ['id' => 56, 'key' => 'newspapers', 'image' => null, 'parent_id' => 55],
        ['id' => 57, 'key' => 'magazines', 'image' => null, 'parent_id' => 55],
        ['id' => 58, 'key' => 'podcasts', 'image' => null, 'parent_id' => 55],
        ['id' => 59, 'key' => 'tv_video', 'image' => null, 'parent_id' => 55],
        ['id' => 60, 'key' => 'blogs', 'image' => null, 'parent_id' => 55],
        ['id' => 61, 'key' => 'professional_services', 'image' => 'test-professional-services.svg', 'parent_id' => null],
        ['id' => 62, 'key' => 'legal_services', 'image' => null, 'parent_id' => 61],
        ['id' => 63, 'key' => 'consulting', 'image' => null, 'parent_id' => 61],
        ['id' => 64, 'key' => 'marketing', 'image' => null, 'parent_id' => 61],
        ['id' => 65, 'key' => 'hr_recruiting', 'image' => null, 'parent_id' => 61],
        ['id' => 66, 'key' => 'printing', 'image' => null, 'parent_id' => 61],
        ['id' => 67, 'key' => 'sports_fitness', 'image' => 'test-sports-and-fitness.svg', 'parent_id' => null],
        ['id' => 68, 'key' => 'gyms', 'image' => null, 'parent_id' => 67],
        ['id' => 69, 'key' => 'sports_clubs', 'image' => null, 'parent_id' => 67],
        ['id' => 70, 'key' => 'outdoor_gear', 'image' => null, 'parent_id' => 67],
        ['id' => 71, 'key' => 'coaching', 'image' => null, 'parent_id' => 67],
        ['id' => 72, 'key' => 'wellness', 'image' => null, 'parent_id' => 67],
    ];

    /**
     * @var array<string, array<string, string>>
     */
    private const TRANSLATIONS = [
        'en' => [
            'technology' => 'Technology',
            'software_development' => 'Software Development',
            'web_hosting' => 'Web Hosting',
            'cybersecurity' => 'Cybersecurity',
            'ai_data' => 'AI & Data',
            'hardware_gadgets' => 'Hardware & Gadgets',
            'business_finance' => 'Business & Finance',
            'banks_credit' => 'Banks & Credit',
            'accounting' => 'Accounting',
            'insurance' => 'Insurance',
            'real_estate' => 'Real Estate',
            'investments' => 'Investments',
            'shopping' => 'Shopping',
            'fashion_stores' => 'Fashion Stores',
            'electronics_stores' => 'Electronics Stores',
            'marketplaces' => 'Marketplaces',
            'office_supplies' => 'Office Supplies',
            'gifts_flowers' => 'Gifts & Flowers',
            'health_medicine' => 'Health & Medicine',
            'clinics' => 'Clinics',
            'pharmacy' => 'Pharmacy',
            'dentistry' => 'Dentistry',
            'mental_health' => 'Mental Health',
            'telemedicine' => 'Telemedicine',
            'education' => 'Education',
            'universities' => 'Universities',
            'online_courses' => 'Online Courses',
            'language_schools' => 'Language Schools',
            'tutoring' => 'Tutoring',
            'science_resources' => 'Science Resources',
            'travel_transport' => 'Travel & Transport',
            'hotels' => 'Hotels',
            'airlines' => 'Airlines',
            'car_rental' => 'Car Rental',
            'logistics' => 'Logistics',
            'travel_guides' => 'Travel Guides',
            'food_dining' => 'Food & Dining',
            'restaurants' => 'Restaurants',
            'coffee_shops' => 'Coffee Shops',
            'grocery_delivery' => 'Grocery Delivery',
            'recipes' => 'Recipes',
            'catering' => 'Catering',
            'home_garden' => 'Home & Garden',
            'furniture' => 'Furniture',
            'interior_design' => 'Interior Design',
            'home_repair' => 'Home Repair',
            'gardening' => 'Gardening',
            'smart_home' => 'Smart Home',
            'entertainment_arts' => 'Entertainment & Arts',
            'movies' => 'Movies',
            'music' => 'Music',
            'games' => 'Games',
            'museums' => 'Museums',
            'events' => 'Events',
            'news_media' => 'News & Media',
            'newspapers' => 'Newspapers',
            'magazines' => 'Magazines',
            'podcasts' => 'Podcasts',
            'tv_video' => 'TV & Video',
            'blogs' => 'Blogs',
            'professional_services' => 'Professional Services',
            'legal_services' => 'Legal Services',
            'consulting' => 'Consulting',
            'marketing' => 'Marketing',
            'hr_recruiting' => 'HR & Recruiting',
            'printing' => 'Printing',
            'sports_fitness' => 'Sports & Fitness',
            'gyms' => 'Gyms',
            'sports_clubs' => 'Sports Clubs',
            'outdoor_gear' => 'Outdoor Gear',
            'coaching' => 'Coaching',
            'wellness' => 'Wellness',
        ],
        'ru' => [
            'technology' => 'Технологии',
            'software_development' => 'Разработка ПО',
            'web_hosting' => 'Хостинг',
            'cybersecurity' => 'Кибербезопасность',
            'ai_data' => 'ИИ и данные',
            'hardware_gadgets' => 'Устройства и гаджеты',
            'business_finance' => 'Бизнес и финансы',
            'banks_credit' => 'Банки и кредиты',
            'accounting' => 'Бухгалтерия',
            'insurance' => 'Страхование',
            'real_estate' => 'Недвижимость',
            'investments' => 'Инвестиции',
            'shopping' => 'Покупки',
            'fashion_stores' => 'Магазины одежды',
            'electronics_stores' => 'Магазины электроники',
            'marketplaces' => 'Маркетплейсы',
            'office_supplies' => 'Офисные товары',
            'gifts_flowers' => 'Подарки и цветы',
            'health_medicine' => 'Здоровье и медицина',
            'clinics' => 'Клиники',
            'pharmacy' => 'Аптеки',
            'dentistry' => 'Стоматология',
            'mental_health' => 'Психическое здоровье',
            'telemedicine' => 'Телемедицина',
            'education' => 'Образование',
            'universities' => 'Университеты',
            'online_courses' => 'Онлайн-курсы',
            'language_schools' => 'Языковые школы',
            'tutoring' => 'Репетиторство',
            'science_resources' => 'Научные ресурсы',
            'travel_transport' => 'Путешествия и транспорт',
            'hotels' => 'Отели',
            'airlines' => 'Авиакомпании',
            'car_rental' => 'Аренда авто',
            'logistics' => 'Логистика',
            'travel_guides' => 'Путеводители',
            'food_dining' => 'Еда и рестораны',
            'restaurants' => 'Рестораны',
            'coffee_shops' => 'Кофейни',
            'grocery_delivery' => 'Доставка продуктов',
            'recipes' => 'Рецепты',
            'catering' => 'Кейтеринг',
            'home_garden' => 'Дом и сад',
            'furniture' => 'Мебель',
            'interior_design' => 'Дизайн интерьера',
            'home_repair' => 'Ремонт дома',
            'gardening' => 'Садоводство',
            'smart_home' => 'Умный дом',
            'entertainment_arts' => 'Развлечения и искусство',
            'movies' => 'Кино',
            'music' => 'Музыка',
            'games' => 'Игры',
            'museums' => 'Музеи',
            'events' => 'События',
            'news_media' => 'Новости и медиа',
            'newspapers' => 'Газеты',
            'magazines' => 'Журналы',
            'podcasts' => 'Подкасты',
            'tv_video' => 'ТВ и видео',
            'blogs' => 'Блоги',
            'professional_services' => 'Профессиональные услуги',
            'legal_services' => 'Юридические услуги',
            'consulting' => 'Консалтинг',
            'marketing' => 'Маркетинг',
            'hr_recruiting' => 'HR и рекрутинг',
            'printing' => 'Печать',
            'sports_fitness' => 'Спорт и фитнес',
            'gyms' => 'Тренажерные залы',
            'sports_clubs' => 'Спортивные клубы',
            'outdoor_gear' => 'Снаряжение для активного отдыха',
            'coaching' => 'Тренерские услуги',
            'wellness' => 'Велнес',
        ],
        'fr' => [
            'technology' => 'Technologie',
            'software_development' => 'Développement logiciel',
            'web_hosting' => 'Hébergement web',
            'cybersecurity' => 'Cybersécurité',
            'ai_data' => 'IA et données',
            'hardware_gadgets' => 'Matériel et gadgets',
            'business_finance' => 'Affaires et finance',
            'banks_credit' => 'Banques et crédit',
            'accounting' => 'Comptabilité',
            'insurance' => 'Assurance',
            'real_estate' => 'Immobilier',
            'investments' => 'Investissements',
            'shopping' => 'Achats',
            'fashion_stores' => 'Boutiques de mode',
            'electronics_stores' => 'Magasins d’électronique',
            'marketplaces' => 'Places de marché',
            'office_supplies' => 'Fournitures de bureau',
            'gifts_flowers' => 'Cadeaux et fleurs',
            'health_medicine' => 'Santé et médecine',
            'clinics' => 'Cliniques',
            'pharmacy' => 'Pharmacies',
            'dentistry' => 'Dentisterie',
            'mental_health' => 'Santé mentale',
            'telemedicine' => 'Télémédecine',
            'education' => 'Éducation',
            'universities' => 'Universités',
            'online_courses' => 'Cours en ligne',
            'language_schools' => 'Écoles de langues',
            'tutoring' => 'Soutien scolaire',
            'science_resources' => 'Ressources scientifiques',
            'travel_transport' => 'Voyage et transport',
            'hotels' => 'Hôtels',
            'airlines' => 'Compagnies aériennes',
            'car_rental' => 'Location de voitures',
            'logistics' => 'Logistique',
            'travel_guides' => 'Guides de voyage',
            'food_dining' => 'Cuisine et restaurants',
            'restaurants' => 'Restaurants',
            'coffee_shops' => 'Cafés',
            'grocery_delivery' => 'Livraison d’épicerie',
            'recipes' => 'Recettes',
            'catering' => 'Traiteur',
            'home_garden' => 'Maison et jardin',
            'furniture' => 'Meubles',
            'interior_design' => 'Design d’intérieur',
            'home_repair' => 'Réparation à domicile',
            'gardening' => 'Jardinage',
            'smart_home' => 'Maison connectée',
            'entertainment_arts' => 'Divertissement et arts',
            'movies' => 'Films',
            'music' => 'Musique',
            'games' => 'Jeux',
            'museums' => 'Musées',
            'events' => 'Événements',
            'news_media' => 'Actualités et médias',
            'newspapers' => 'Journaux',
            'magazines' => 'Magazines',
            'podcasts' => 'Podcasts',
            'tv_video' => 'TV et vidéo',
            'blogs' => 'Blogs',
            'professional_services' => 'Services professionnels',
            'legal_services' => 'Services juridiques',
            'consulting' => 'Conseil',
            'marketing' => 'Marketing',
            'hr_recruiting' => 'RH et recrutement',
            'printing' => 'Impression',
            'sports_fitness' => 'Sport et fitness',
            'gyms' => 'Salles de sport',
            'sports_clubs' => 'Clubs sportifs',
            'outdoor_gear' => 'Équipement de plein air',
            'coaching' => 'Coaching',
            'wellness' => 'Bien-être',
        ],
        'de' => [
            'technology' => 'Technologie',
            'software_development' => 'Softwareentwicklung',
            'web_hosting' => 'Webhosting',
            'cybersecurity' => 'Cybersicherheit',
            'ai_data' => 'KI und Daten',
            'hardware_gadgets' => 'Hardware und Gadgets',
            'business_finance' => 'Wirtschaft und Finanzen',
            'banks_credit' => 'Banken und Kredit',
            'accounting' => 'Buchhaltung',
            'insurance' => 'Versicherungen',
            'real_estate' => 'Immobilien',
            'investments' => 'Investitionen',
            'shopping' => 'Shopping',
            'fashion_stores' => 'Modegeschäfte',
            'electronics_stores' => 'Elektronikgeschäfte',
            'marketplaces' => 'Marktplätze',
            'office_supplies' => 'Bürobedarf',
            'gifts_flowers' => 'Geschenke und Blumen',
            'health_medicine' => 'Gesundheit und Medizin',
            'clinics' => 'Kliniken',
            'pharmacy' => 'Apotheken',
            'dentistry' => 'Zahnmedizin',
            'mental_health' => 'Psychische Gesundheit',
            'telemedicine' => 'Telemedizin',
            'education' => 'Bildung',
            'universities' => 'Universitäten',
            'online_courses' => 'Online-Kurse',
            'language_schools' => 'Sprachschulen',
            'tutoring' => 'Nachhilfe',
            'science_resources' => 'Wissenschaftsressourcen',
            'travel_transport' => 'Reisen und Transport',
            'hotels' => 'Hotels',
            'airlines' => 'Fluggesellschaften',
            'car_rental' => 'Autovermietung',
            'logistics' => 'Logistik',
            'travel_guides' => 'Reiseführer',
            'food_dining' => 'Essen und Gastronomie',
            'restaurants' => 'Restaurants',
            'coffee_shops' => 'Cafés',
            'grocery_delivery' => 'Lebensmittellieferung',
            'recipes' => 'Rezepte',
            'catering' => 'Catering',
            'home_garden' => 'Haus und Garten',
            'furniture' => 'Möbel',
            'interior_design' => 'Innenarchitektur',
            'home_repair' => 'Hausreparatur',
            'gardening' => 'Gartenarbeit',
            'smart_home' => 'Smart Home',
            'entertainment_arts' => 'Unterhaltung und Kunst',
            'movies' => 'Filme',
            'music' => 'Musik',
            'games' => 'Spiele',
            'museums' => 'Museen',
            'events' => 'Veranstaltungen',
            'news_media' => 'Nachrichten und Medien',
            'newspapers' => 'Zeitungen',
            'magazines' => 'Magazine',
            'podcasts' => 'Podcasts',
            'tv_video' => 'TV und Video',
            'blogs' => 'Blogs',
            'professional_services' => 'Professionelle Dienstleistungen',
            'legal_services' => 'Rechtsdienstleistungen',
            'consulting' => 'Beratung',
            'marketing' => 'Marketing',
            'hr_recruiting' => 'HR und Recruiting',
            'printing' => 'Druck',
            'sports_fitness' => 'Sport und Fitness',
            'gyms' => 'Fitnessstudios',
            'sports_clubs' => 'Sportvereine',
            'outdoor_gear' => 'Outdoor-Ausrüstung',
            'coaching' => 'Coaching',
            'wellness' => 'Wellness',
        ],
        'es' => [
            'technology' => 'Tecnología',
            'software_development' => 'Desarrollo de software',
            'web_hosting' => 'Alojamiento web',
            'cybersecurity' => 'Ciberseguridad',
            'ai_data' => 'IA y datos',
            'hardware_gadgets' => 'Hardware y gadgets',
            'business_finance' => 'Negocios y finanzas',
            'banks_credit' => 'Bancos y crédito',
            'accounting' => 'Contabilidad',
            'insurance' => 'Seguros',
            'real_estate' => 'Bienes raíces',
            'investments' => 'Inversiones',
            'shopping' => 'Compras',
            'fashion_stores' => 'Tiendas de moda',
            'electronics_stores' => 'Tiendas de electrónica',
            'marketplaces' => 'Marketplaces',
            'office_supplies' => 'Material de oficina',
            'gifts_flowers' => 'Regalos y flores',
            'health_medicine' => 'Salud y medicina',
            'clinics' => 'Clínicas',
            'pharmacy' => 'Farmacias',
            'dentistry' => 'Odontología',
            'mental_health' => 'Salud mental',
            'telemedicine' => 'Telemedicina',
            'education' => 'Educación',
            'universities' => 'Universidades',
            'online_courses' => 'Cursos en línea',
            'language_schools' => 'Escuelas de idiomas',
            'tutoring' => 'Tutorías',
            'science_resources' => 'Recursos científicos',
            'travel_transport' => 'Viajes y transporte',
            'hotels' => 'Hoteles',
            'airlines' => 'Aerolíneas',
            'car_rental' => 'Alquiler de coches',
            'logistics' => 'Logística',
            'travel_guides' => 'Guías de viaje',
            'food_dining' => 'Comida y restaurantes',
            'restaurants' => 'Restaurantes',
            'coffee_shops' => 'Cafeterías',
            'grocery_delivery' => 'Entrega de comestibles',
            'recipes' => 'Recetas',
            'catering' => 'Catering',
            'home_garden' => 'Hogar y jardín',
            'furniture' => 'Muebles',
            'interior_design' => 'Diseño de interiores',
            'home_repair' => 'Reparación del hogar',
            'gardening' => 'Jardinería',
            'smart_home' => 'Hogar inteligente',
            'entertainment_arts' => 'Entretenimiento y arte',
            'movies' => 'Películas',
            'music' => 'Música',
            'games' => 'Juegos',
            'museums' => 'Museos',
            'events' => 'Eventos',
            'news_media' => 'Noticias y medios',
            'newspapers' => 'Periódicos',
            'magazines' => 'Revistas',
            'podcasts' => 'Podcasts',
            'tv_video' => 'TV y video',
            'blogs' => 'Blogs',
            'professional_services' => 'Servicios profesionales',
            'legal_services' => 'Servicios legales',
            'consulting' => 'Consultoría',
            'marketing' => 'Marketing',
            'hr_recruiting' => 'RR. HH. y selección',
            'printing' => 'Impresión',
            'sports_fitness' => 'Deportes y fitness',
            'gyms' => 'Gimnasios',
            'sports_clubs' => 'Clubes deportivos',
            'outdoor_gear' => 'Equipo para exteriores',
            'coaching' => 'Coaching',
            'wellness' => 'Bienestar',
        ],
    ];

    /**
     * @var array<string, string>
     */
    private const DESCRIPTION_TEMPLATES = [
        'en' => '%s websites and useful resources for a curated link directory.',
        'ru' => 'Сайты и полезные ресурсы раздела «%s» для каталога ссылок.',
        'fr' => 'Sites web et ressources utiles de la section « %s » pour un annuaire de liens.',
        'de' => 'Websites und nützliche Ressourcen aus dem Bereich „%s“ für ein Linkverzeichnis.',
        'es' => 'Sitios web y recursos útiles de la sección «%s» para un directorio de enlaces.',
    ];

    /**
     * @var array<string, string>
     */
    private const KEYWORD_SUFFIXES = [
        'en' => 'directory, links, catalog',
        'ru' => 'каталог, ссылки, сайты',
        'fr' => 'annuaire, liens, catalogue',
        'de' => 'verzeichnis, links, katalog',
        'es' => 'directorio, enlaces, catálogo',
    ];

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        if (Catalog::query()->exists()) {
            return;
        }

        Catalog::unguarded(function (): void {
            foreach ($this->categories() as $category) {
                Catalog::create($category);
            }
        });
    }

    /**
     * Build localized default catalog sections for the selected installer locale.
     *
     * @return array<int, array<string, mixed>>
     */
    private function categories(): array
    {
        $locale = $this->locale();
        $names = self::TRANSLATIONS[$locale] ?? self::TRANSLATIONS['en'];

        return array_map(
            fn (array $category): array => $this->category(
                (int) $category['id'],
                $names[$category['key']] ?? self::TRANSLATIONS['en'][$category['key']],
                $category['image'],
                $category['parent_id'] === null ? null : (int) $category['parent_id'],
                $locale,
            ),
            self::CATALOG,
        );
    }

    /**
     * Resolve the locale used for installer seed data.
     */
    private function locale(): string
    {
        $locale = config('app.locale');

        if (in_array($locale, config('app.locales', []), true) && isset(self::TRANSLATIONS[$locale])) {
            return $locale;
        }

        $fallbackLocale = config('app.fallback_locale', 'en');

        return isset(self::TRANSLATIONS[$fallbackLocale]) ? $fallbackLocale : 'en';
    }

    /**
     * Build one catalog row from localized seed data.
     */
    private function category(int $id, string $name, ?string $image, ?int $parentId, string $locale): array
    {
        return [
            'id' => $id,
            'name' => $name,
            'description' => sprintf(self::DESCRIPTION_TEMPLATES[$locale] ?? self::DESCRIPTION_TEMPLATES['en'], $name),
            'keywords' => mb_strtolower($name).', '.(self::KEYWORD_SUFFIXES[$locale] ?? self::KEYWORD_SUFFIXES['en']),
            'image' => $image,
            'parent_id' => $parentId,
        ];
    }
}
