memory_limit=512M
upload_max_filesize=64M
post_max_size=64M
max_execution_time=300
max_input_vars=5000
date.timezone=Europe/Moscow

opcache.enable=1
opcache.validate_timestamps=1
opcache.memory_consumption=192
opcache.max_accelerated_files=20000
